### ISSUE TITLE
Save image to a folder

### ISSUE THREAD

**Issue by balumuriraj** [Lith/strapi-provider-upload-google-cloud-storage#1]
How can i configure the plugin or strapi to save the image to a folder on the bucket?

On the strapi configuration page, I see only the following options:

![Screen Shot 2019-06-27 at 12 10 25 PM](https://user-images.githubusercontent.com/4073294/60293677-93b34980-98d4-11e9-8259-2e629d27eb48.png)

I tried using `test.appspot.com\images` as the bucket name, but strapi threw an error.

**Comment by Lith** [comment]
Hi, 

When you upload a new file you can defined the path directly from strapi args like that (with ref, refId, field, ...) : 

```
 const formData = new FormData();
    formData.append('files', file[0]);
    formData.append('ref', ref);
    formData.append('refId', refId);
    formData.append('field', type);
    formData.append('path', 'users/' + userId);
```
The folder will be created automatically, and the media will be uploaded into.

I will check if I can add a default folder in Bucket.

**Comment by cpres** [comment]
Just tested this and when I add 
```
formData.append('path', 'testfolder/');
```
It continues to upload into the random 32 digit folder instead of mine, something like "4be815a61d504993b8a2702760aa3fa7", and different every time (which is HORRIBLE!!)

I noticed the docs say this:
`path: (optional): The folder where the file(s) will be uploaded to (only supported on strapi-provider-upload-aws-s3 now).`

Obviously I'm a much bigger fan of google cloud, so I'm hoping we can get the append to work with this package as well :)

**Comment by kalanyuz** [comment]
@cpres 
probably the '/' is the problem. Try uploading without one. Works fine for me.
