### ISSUE TITLE
Use base64 encoded credentials input instead of raw text

### ISSUE THREAD

**Issue by kalanyuz** [Lith/strapi-provider-upload-google-cloud-storage#10]
**Is your feature request related to a problem? Please describe.**
- Security issues. This suggestion is from observing how Github action does it.

**Describe the solution you'd like**
Use base64 encoded credentials input instead of raw text

**Additional context**
If this is agreed I'll implement and make a PR.

**Comment by alidawud** [comment]
Use base64 doesn't make any different. people can still decrypt it.
Giving a limited permission to the service account might be a better way:

- Create a [service account](https://console.cloud.google.com/apis/credentials/serviceaccountkey) with no role & permission.
- Create a [Multi-Regional Bucket](https://console.cloud.google.com/storage/browser/)  and add the service account with `Storage Admin` Permission
- Go to Strapi plugin setting page to set service account json and bucket name for upload plugin.

**Comment by Lith** [comment]
Hi @kalanyuz, 

Thanks for your proposition, but I agree with @alidawud.
"Base64" is not an encrypted system, it's a storage solution basically used to store data like an image.

If you need to secure your system, you can create a limited access (cf. solution of @alidawud) or maybe you can develop a solution with a local file reading (instead of raw text).
The file can be store on your server instead of your database ?

I will try to think about it and find a better way.

Thanks,

**Comment by Lith** [comment]
#12 solution // relate to
