### ISSUE TITLE
Cannot use with version 3.0.0-beta.16.5

### ISSUE THREAD

**Issue by sharpn** [Lith/strapi-provider-upload-google-cloud-storage#26]
**Describe the bug**
When I am trying to use this with version 3.0.0-beta.16.5 os strapi I just get a blank box in the upload settings section

**To Reproduce**
1. Use the latest npx to create a new strapi project
2. Install the google-cloud-storage plugin
3. Visit the upload setting section in the admin panel
4. The dropdown box shows `local` and `blank`

**Expected behavior**
Should be able to configure google cloud storage upload from the admin panel

**Screenshots**
<img width="1174" alt="Screenshot 2020-05-12 at 16 07 47" src="https://user-images.githubusercontent.com/8088671/81710602-c3c2f700-946a-11ea-9d4e-54a0e734975b.png">

**Desktop (please complete the following information):**
 - OS: macOs Catalina
 - Browser: chrome
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context**

**Comment by Lith** [comment]
Hello @sharpn,

I think you are trying to use latest release of the plugin 20.3 with Strapi 16.5.
Try with the release `18.8` : 
- https://www.npmjs.com/package/strapi-provider-upload-google-cloud-storage/v/3.0.0-beta.18.8

You will have all configuration available via the Strapi Administration.

Otherwise, it will be interesting to migrate to strapi 17, then 18, then 19, and... finally 20 :) 
Keeping a project up to date is important.

Thanks,

**Comment by sharpn** [comment]
Thanks. Got it working with the latest release of strapi
