### ISSUE TITLE
Reference to file different from check existence

### ISSUE THREAD

**Issue by dgmike** [Lith/strapi-provider-upload-google-cloud-storage#30]
This line is different from line checking if file exists. Is it right?

https://github.com/Lith/strapi-provider-upload-google-cloud-storage/blob/d1177c2ee0f9c6d4d37703ac6c46fbc550e0c498/lib/index.js#L115

https://github.com/Lith/strapi-provider-upload-google-cloud-storage/blob/d1177c2ee0f9c6d4d37703ac6c46fbc550e0c498/lib/index.js#L126

**Comment by Lith** [comment]
Hi @dgmike :) 

It's a good question !
When we create a new file, call `my-awesome-file.jpg` , the file name contains `my-awesome-file.jpg`.
So we need to add the `filePath` in order to have the full url.

But, if the file already exist and we need to remove it, we need to give only the `fileName`.

Not sure if it's clear, but on Google Storage the "upload" and "delete" defer a little bit.

Thanks

**Comment by dgmike** [comment]
I see...
