### ISSUE TITLE
Non public accessible files

### ISSUE THREAD

**Issue by piotkaba-pearson** [Lith/strapi-provider-upload-google-cloud-storage#31]
Currently files on a storage are saved with `public: true`.
In my project resources that are stored on GCS are private by their nature and exposing them publicly is inappropriate even with a hash added to a file name.

**Possible solution**
To keep files private and to allow them to be visible by strapi admin panel a wrapper could be provided which will resolve provided gcp credentials and pass required file.

Such approach could be configured if allowing public access is fine and to avoid additional layer if not necessary.

**Comment by Lith** [comment]
Hello @piotkaba-pearson !

Thanks for your issue. 

We can add an optional variable than will change the « public » value if you want to keep files privates.

Quick solutions :
- You can send a PR with this new feature. 
- You can fork and use your own version of the plugin for your project.

Otherwise I will try to add this later this month :)

Be careful about one thing, files will maybe not available from Strapi Admin and Media Library.

Thanks,

**Comment by Lith** [comment]
Thanks to @dgmike for his contribution !

This new feature will be available with stable release "3.0.0" 
I will publish the new release on Friday (I hope ^^).

Thanks :)
