### ISSUE TITLE
path does not exist

### ISSUE THREAD

**Issue by wallythewebdev** [Lith/strapi-provider-upload-google-cloud-storage#71]
Hi there, 

im using stapi: 3.0.5

The path requested to update in your DOCS - `extensions/upload/config/settings.json`
is not found in my version of strapi? Do I need to created this path then to use this package? 

also, do I need to define the data that is being placed in, settings.json? i.e. 

{
    "provider": "google-cloud-storage",
    "providerOptions": {
      "bucketName": "Bucket-name"
    }
  }

does that need to be defined first as: `let GAP = {}` << for example

-- Desired outcome: 

Provide more clarity on how to set up this package in the DOC - 

Thanks in advance for any help, 
W

**Comment by Lith** [comment]
Hi @wallythewebdev 

Yes, you need to create the file, but you can also add this configuration in the new `plugin.js` file in config folder.

We provide many example of implementation, in order to help everybody, but maybe I need to update it, this take some time... 
So let me check the latest release, release yesterday only :) 

Try to add the upload provider configuration in this file : `config/plugins.js`
```
module.exports = {
  upload: {
    enabled: true,
    name: 'Local server',
    sizeLimit: 1000000,
    provider: 'google-cloud-storage',
    bucketName: '#bucket-name#',
    serviceAccount: '#copy your service account in json#',
    baseUrl: 'https://storage.googleapis.com/{bucket-name}',
  },
};
```

Thanks,

**Comment by Lith** [comment]
@wallythewebdev 

A new release for latest Strapi version (3.1.5) is now available.
The `README.md` has been update too.

If all of this information or ok for you, you're free to close this issue :) 
Thanks,

**Comment by wallythewebdev** [comment]
Hi @Lith , 

Thank you for your reply. 

I spent some time with the Strapi Dev on slack and was able to work out the road bumps in my method. 

I'll close this now. 
Thanks again, 
W
