### ISSUE TITLE
[New functionality] Dynamic path based on property name

### ISSUE THREAD

**Issue by umbertix** [Lith/strapi-provider-upload-google-cloud-storage#82]
Let's imagine the next user case:
- I have a custom model (Application)
	- With multiple file properties (icon, screenshot, etc...)
- I want to use cloud storage

At the current moment the path that is set with in the `providerOptions: { basePath: 'myCustomPath' },` is where all the uploads would go. It's not a massive problem but if you ever want to take a quick look at the actual assets that you have, it would be nearly impossible to make a correlation unless that you have the DB, to point you to the correct file relation.

**Describe the solution you'd like**
It would be great if the path could be constructed dynamically based on properties of the model or defined in the model details.
For example, with in the model definition: `
"icon": {
"model": "file",
"via": "related",
"allowedTypes": [
  "images"
],
"appendToPath": "${properties.name}/assets/icons"
"plugin": "upload",
},`

**Describe alternatives you've considered**
Alternatively would be nice if the `providerOptions` could take that in cosideration.
For example:  `providerOptions: { basePath: '${model.property1}/${model.property2}' },`

**Comment by Frank3K** [comment]
I'd like to have this functionality too and therefore I have started looking into it. I think the model data is currently not available in the plugin since strapi [does not seem to provide it](https://github.com/strapi/strapi/blob/4ab210eec65d7f1a4f6334cdef4c797b4e6b9531/packages/strapi-plugin-upload/services/Upload.js#L154):

```js
    await strapi.plugins.upload.provider.upload(fileData);
```

Therefore it would require a change in strapi too.

Even if the data was provided, how would you handle the following cases?

1. The file is uploaded when the referenced properties have not yet been filled in.
2. The referenced properties change. That would 'break' the (logical/virtual) link between the file and the model.
3. How would you handle uploads in the _Media Library_ where no model is present?

**Comment by Frank3K** [comment]
I've just found [this thread](https://forum.strapi.io/t/modify-upload-provider-with-custom-path/578/7) and after reading that I'm not sure if we're talking about the same thing. I think you're talking about the API, my comment is more about the strapi CMS.
