### ISSUE TITLE
Images are placed into folders with the same name as an image

### ISSUE THREAD

**Issue by milos5593** [Lith/strapi-provider-upload-google-cloud-storage#89]
I know that this thing is supposed to be fixed by this #53, but somehow I still get the exact same error, images are first placed into a folder with the same name instead of just uploading them to the bucket.

My config for the plugin is:

``` javascript
module.exports = ({ env }) => ({
  upload: {
    provider: "google-cloud-storage",
    providerOptions: {
      serviceAccount: {/* config from the service account is here *\},
      bucketName: "public_crauto",
      basePath: "website",
      baseUrl: "https://storage.googleapis.com/public_crauto",
      publicFiles: true,
      uniform: false,
    },
  },
});
```

Is there a config that I am missing or something?

I use Strapi version `3.5.4`, and this plugin version `3.4.6`

**Comment by Frank3K** [comment]
This situation happens when both `file.related` and `file.path` are undefined.

https://github.com/Lith/strapi-provider-upload-google-cloud-storage/blob/f7b6167920906d71d883f8b36cce9e9d7c3fe9f4/lib/provider.js#L122-L129

I'm not sure what the right (desired) solution would be. Another thing I noticed is that one part is slugified and the other isn't.

**Comment by 1adetbeyfendi** [comment]
This is temporarily resolved.

```

 
  if (file.hash.match(/large_|medium_|small_|thumbnail_/g) !== null) {
    // TODO:
    file.related = [];
    file.related.push({
      ref: file.hash.replace(/large_|medium_|small_|thumbnail_/g, ''),
    });
  }

```

**Comment by fborgherodbsagency** [comment]
**Still experiencing the issue with the latest version is that merged in the latest version?**
